<GRAMMAR> ::= <ASSIGNMENT> <GRAMMAR_PRIME>
<GRAMMAR_PRIME> ::= <GRAMMAR> | #e

<ASSIGNMENT> ::= NON_TERMINAL ASSIGNMENT_SYMBOL <OR_EXPR> NEWLINE

<OR_EXPR> ::= <SEQ_EXPR> <OR_EXPR_PRIME>
<OR_EXPR_PRIME> ::= OR <OR_EXPR> | #e

<SEQ_EXPR> ::= <TERM> <SEQ_EXPR_PRIME>
<SEQ_EXPR_PRIME> ::= <SEQ_EXPR> | #e

<TERM> ::= NON_TERMINAL | TERMINAL | EPSILON
