<ASSIGNMENT> ::= NON_TERMINAL ASSIGNMENT_SYMBOL <EXPR>
<EXPR> ::= <OR_EXPR>
<OR_EXPR> ::= <SEQ_EXPR> OR <OR_EXPR> | <SEQ_EXPR>
<SEQ_EXPR> ::= <PRI_EXPR> <SEQ_EXPR> | <PRI_EXPR>
<PRI_EXPR> ::= <TERM> | LBRACE <EXPR> RBRACE
<TERM> ::= NON_TERMINAL | TERMINAL | EPSILON
